### ISSUE TITLE
Question: How to customize resolver IP?

### ISSUE THREAD

**Issue by TangRufus** [bibendi/dip#100]
The doc uses `127.0.0.1` for `*.docker`.

https://github.com/bibendi/dip/blob/3e5f464e26f7c3d3c758034aee5eb8c5376749c4/docs/docker-for-mac-install.md#L15-L28

Background: I have [valet](https://github.com/laravel/valet) (think puma-dev for php) installed which occupies `127.0.0.1`. Following the steps in the docs, my `dip-rails.docker` resolved to valet.

Tried to use `127.0.123.1` and `172.17.0.1`(as in https://github.com/aacebedo/dnsdock/blob/1b558dc15527c149fc540f8934116e7791a8b994/readme.md#L291-L294). `dip-rails.docker` failed to resolve to docker in both cases (`ERR_NAME_NOT_RESOLVED`).

Question: How to customize resolver IP?

Thanks!!!

**Comment by bibendi** [comment]
The Valet's readme says that it already has running its own dnsmasq and nginx. I think you should run your rails project something like this `dip-rails.docker:3000`, because I believe the 80 port is already used by the Valet nginx.

Anyway, I don't use macOS for years, and I can't help you better with this question, sorry.
