### ISSUE TITLE
Feature request: additional docker-compose options supports

### ISSUE THREAD

**Issue by sjoonk** [bibendi/dip#108]
When I run `dip run` command, it only accept two options currently: -p and -e options.

On the original docker-compose, there are other options to use like -d, -u, -v, etc.

Can you support these options?

**Comment by bibendi** [comment]
Hi,
Just wondering, what is your use case? We already support extended Docker-Compose options in the dip.yml config because Dip it's a shorthand wrapper to hide the usage complexity of Docker-Compose.

![image](https://user-images.githubusercontent.com/320886/103193204-c89ac500-48ec-11eb-9376-fff9ba00e49f.png)

**Comment by sjoonk** [comment]
I'm sorry. I can't see the compose `run_options` options! My mistake! Thank you!!
